services:
  mongo:
    image: 'mongo'
    volumes:
      - ./db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    restart: unless-stopped
  main:
    build: .
    command: main
    ports:
      - "8008:8008"
    depends_on:
      - mongo
    restart: unless-stopped
    environment:
      HTTP_BIND: 0.0.0.0:8008
      HTTP_BIND_SOCKET_ONLY: false
      HTTP_CORS_HOSTS: http://localhost:8080
      DB_URL: mongodb://root:toor@mongo:27017/
      DB_NAME: actix-mongo
      AUTH_JWT_SECRET: cHangEmePleaSe
      AUTH_JWT_EXPIRE_HOUR: 24
# trace for development
      RUST_LOG: trace
# info for production
#      RUST_LOG: info